services:
  db:
    image: postgres:latest
    container_name: compose_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alexsirotin!
      POSTGRES_DB: phonebook
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/phonebook

  phonebook:
    build: .
    container_name: phonebook-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/phonebook
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: alexsirotin!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
volumes:
  postgres-data:

